name: Common CI
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
      app_type:
        required: true
        type: string
jobs:
  Download-Dependencies:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Download Dependencies
        run: |
          if [ ${{inputs.app_type}} == nodejs ]; then
            npm install
          elif [ ${{inputs.app_type}} == maven ]; then
            mvn package
          fi
      - name: Check files
        run: ls -l

  Docker-Build:
    runs-on: self-hosted
    needs: Download-Dependencies
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Build
        run: |
          docker build -t 160885265516.dkr.ecr.us-east-1.amazonaws.com/${{inputs.project_name}}/${{inputs.component_name}}:${GITHUB_SHA} .
    

      - name: Docker Push
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          docker push 160885265516.dkr.ecr.us-east-1.amazonaws.com/${{inputs.project_name}}/${{inputs.component_name}}:${GITHUB_SHA}